version: "3.9"
services:
  backend:
    build: ./backend
    ports:
      - "8000:8000"
  mysql:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: 
      MYSQL_DATABASE: llm_search_db
    ports:
      - "3306:3306"